os: linux
language:
- minimal
services:
- docker

env:
- OS_FAMILY=centos OS_VERSION=7
- OS_FAMILY=centos OS_VERSION=8
- OS_FAMILY=debian OS_VERSION=10
- OS_FAMILY=fedora OS_VERSION=30
- OS_FAMILY=fedora OS_VERSION=31
- OS_FAMILY=ubuntu OS_VERSION=18.04
- OS_FAMILY=ubuntu OS_VERSION=19.04

script:
- lscpu && uname -a && docker version
- travis_wait 360 ./scripts/docker_build.sh

after_success:
- ./scripts/docker_deploy.sh