name: ci_dockerfile
on:
  push:
    branches:
      - develop
jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, debian-10, centos-8, fedora-30, fedora-31]
        include:
          - os: ubuntu-18.04
            family: ubuntu
            version: 18.04
          - os: ubuntu-20.04
            family: ubuntu
            version: 20.04
          - os: debian-10
            family: debian
            version: 10
          - os: centos-8
            family: centos
            version: 8
          - os: fedora-30
            family: fedora
            version: 30
          - os: fedora-31
            family: fedora
            version: 31
    steps:
      - uses: actions/checkout@master
      - name: build
        run: |
          docker build -t fastide/toolbox-${{ matrix.family }}:${{ matrix.version  }} --build-arg OS_FAMILY=${{ matrix.family }} --build-arg OS_VERSION=${{ matrix.version  }} .
